"""empty message

Revision ID: 31d925d4716d
Revises: dc1cc911b2f1
Create Date: 2020-11-06 19:40:22.870100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31d925d4716d'
down_revision = 'dc1cc911b2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_item_snapshot',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('stock_item_id', postgresql.UUID(), nullable=False),
    sa.Column('maintainer_id', postgresql.UUID(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['maintainer_id'], ['maintainer.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_item.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('stock_item', 'quantity')
    op.drop_column('stock_item', 'unit_of_measure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_item', sa.Column('unit_of_measure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stock_item', sa.Column('quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('stock_item_snapshot')
    op.drop_table('unit_of_measure')
    # ### end Alembic commands ###
